name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -ntp -B install
      - name: JPMS sanity check
        run: |
          JAR_FILE=$(ls target/zip-prefixer-*.jar | grep -Ev '(-sources|-tests|-javadoc)' | head -n 1)
          jar --describe-module --file "$JAR_FILE"
      - name: Run our test suite
        run: |
          sudo apt-get -y install p7zip
          src/it/resources/run-integration-test.sh
